version: '2'

services:
  postgres:
    image: 'postgres:9.4.5'
    environment:
      POSTGRES_USER: 'mobydock'
      POSTGRES_PASSWORD: 'yourpassword'
    ports:
      - '5432:5432'
    volumes:
      - 'postgres:/var/lib/postgresql/data'

  redis:
    image: 'redis:5.0.8'
    volumes:
      - 'redis:/data'

  mobydock:
    build: '.'
    depends_on:
      - 'postgres'
      - 'redis'
    volumes:
      - '.:/app'
    env_file:
      - '.env'
    ports:
      - '8000:8000'

volumes:
  postgres: {}
  redis: {}
